# 数据库配置
database:
  host: localhost
  port: 3306
  username: root
  password: your_password
  dbname: lottery_draw
  charset: utf8mb4
  parse_time: true
  loc: Local
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

# JWT配置
jwt:
  secret: your_jwt_secret_key
  expire_duration: 2h
  refresh_token_expire: 720h  # 30天
